language: php
php:
  - 7.4
  - 8.0
  - 8.1
  - hhvm

sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.0.0"
  - travis_retry composer install --no-interaction

script: ./vendor/bin/phpunit -c tests/phpunit.xml tests/