language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.0.0"
  - composer install --dev --no-interaction

script: ./vendor/bin/phpunit -c tests/phpunit.xml tests/